// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj3zTnxP1hSca2ejF961t_Bbu2fhqKZgU',
    appId: '1:127618949659:web:2cfaf350192e4907020ebe',
    messagingSenderId: '127618949659',
    projectId: 'ai-fusion-e3046',
    authDomain: 'ai-fusion-e3046.firebaseapp.com',
    storageBucket: 'ai-fusion-e3046.appspot.com',
    measurementId: 'G-R7MV1DKS6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfom3zt9sgT1wnRt6pJbpUs8hRnFYDz2w',
    appId: '1:127618949659:android:a9bb5a7f13a43085020ebe',
    messagingSenderId: '127618949659',
    projectId: 'ai-fusion-e3046',
    storageBucket: 'ai-fusion-e3046.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIitE-Lp6m7gCYVF-aJZ5xpZ9jdPv0P44',
    appId: '1:127618949659:ios:7a1d7f847fbbb925020ebe',
    messagingSenderId: '127618949659',
    projectId: 'ai-fusion-e3046',
    storageBucket: 'ai-fusion-e3046.appspot.com',
    iosBundleId: 'com.example.ridebhaiya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIitE-Lp6m7gCYVF-aJZ5xpZ9jdPv0P44',
    appId: '1:127618949659:ios:7a1d7f847fbbb925020ebe',
    messagingSenderId: '127618949659',
    projectId: 'ai-fusion-e3046',
    storageBucket: 'ai-fusion-e3046.appspot.com',
    iosBundleId: 'com.example.ridebhaiya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj3zTnxP1hSca2ejF961t_Bbu2fhqKZgU',
    appId: '1:127618949659:web:630975b19f33df47020ebe',
    messagingSenderId: '127618949659',
    projectId: 'ai-fusion-e3046',
    authDomain: 'ai-fusion-e3046.firebaseapp.com',
    storageBucket: 'ai-fusion-e3046.appspot.com',
    measurementId: 'G-3Q74F4Q3G0',
  );
}
